In [2]:
import pandas as pd
import numpy as np
import random as rd

dataset=pd.read_csv('Mall_Customers.csv')
dataset.head()

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [3]:
X = dataset.iloc[:, [3, 4]].values
X

array([[ 15,  39],
       [ 15,  81],
       [ 16,   6],
       [ 16,  77],
       [ 17,  40],
       [ 17,  76],
       [ 18,   6],
       [ 18,  94],
       [ 19,   3],
       [ 19,  72],
       [ 19,  14],
       [ 19,  99],
       [ 20,  15],
       [ 20,  77],
       [ 20,  13],
       [ 20,  79],
       [ 21,  35],
       [ 21,  66],
       [ 23,  29],
       [ 23,  98],
       [ 24,  35],
       [ 24,  73],
       [ 25,   5],
       [ 25,  73],
       [ 28,  14],
       [ 28,  82],
       [ 28,  32],
       [ 28,  61],
       [ 29,  31],
       [ 29,  87],
       [ 30,   4],
       [ 30,  73],
       [ 33,   4],
       [ 33,  92],
       [ 33,  14],
       [ 33,  81],
       [ 34,  17],
       [ 34,  73],
       [ 37,  26],
       [ 37,  75],
       [ 38,  35],
       [ 38,  92],
       [ 39,  36],
       [ 39,  61],
       [ 39,  28],
       [ 39,  65],
       [ 40,  55],
       [ 40,  47],
       [ 40,  42],
       [ 40,  42],
       [ 42,  52],
       [ 42,  60],
       [ 43,

In [4]:
m=X.shape[0] #number of training examples
n=X.shape[1] #number of features. Here n=2
n_iter=100

In [5]:
K=5 # number of clusters
Centroids=np.array([]).reshape(n,0) 
print(Centroids.shape)

(2, 0)


In [6]:
for i in range(K):
    rand=rd.randint(0,m-1)
    print('rand',rand)
    print('X[rand]',X[rand])
    print('Centroids',Centroids)
    print('---------------')
    Centroids=np.c_[Centroids,X[rand]]#addind values along with the second axis. does transpose and them concatenate
    print(Centroids)
    print('*********')
print('---------------')
print('Centroids', Centroids)

rand 28
X[rand] [29 31]
Centroids []
---------------
[[29.]
 [31.]]
*********
rand 91
X[rand] [59 41]
Centroids [[29.]
 [31.]]
---------------
[[29. 59.]
 [31. 41.]]
*********
rand 193
X[rand] [113  91]
Centroids [[29. 59.]
 [31. 41.]]
---------------
[[ 29.  59. 113.]
 [ 31.  41.  91.]]
*********
rand 144
X[rand] [77 12]
Centroids [[ 29.  59. 113.]
 [ 31.  41.  91.]]
---------------
[[ 29.  59. 113.  77.]
 [ 31.  41.  91.  12.]]
*********
rand 153
X[rand] [78 76]
Centroids [[ 29.  59. 113.  77.]
 [ 31.  41.  91.  12.]]
---------------
[[ 29.  59. 113.  77.  78.]
 [ 31.  41.  91.  12.  76.]]
*********
---------------
Centroids [[ 29.  59. 113.  77.  78.]
 [ 31.  41.  91.  12.  76.]]


In [7]:
Centroids

array([[ 29.,  59., 113.,  77.,  78.],
       [ 31.,  41.,  91.,  12.,  76.]])

In [8]:
EuclidianDistance=np.array([]).reshape(m,0)
for k in range(K):
    tempDist=np.sum((X-Centroids[:,k])**2,axis=1)#tempDist will be an array
    print('tempDist',tempDist)
    EuclidianDistance=np.c_[EuclidianDistance,tempDist]
C=np.argmin(EuclidianDistance,axis=1)+1
print(C)

tempDist [2.6000e+02 2.6960e+03 7.9400e+02 2.2850e+03 2.2500e+02 2.1690e+03
 7.4600e+02 4.0900e+03 8.8400e+02 1.7810e+03 3.8900e+02 4.7240e+03
 3.3700e+02 2.1970e+03 4.0500e+02 2.3850e+03 8.0000e+01 1.2890e+03
 4.0000e+01 4.5250e+03 4.1000e+01 1.7890e+03 6.9200e+02 1.7800e+03
 2.9000e+02 2.6020e+03 2.0000e+00 9.0100e+02 0.0000e+00 3.1360e+03
 7.3000e+02 1.7650e+03 7.4500e+02 3.7370e+03 3.0500e+02 2.5160e+03
 2.2100e+02 1.7890e+03 8.9000e+01 2.0000e+03 9.7000e+01 3.8020e+03
 1.2500e+02 1.0000e+03 1.0900e+02 1.2560e+03 6.9700e+02 3.7700e+02
 2.4200e+02 2.4200e+02 6.1000e+02 1.0100e+03 7.2500e+02 1.0370e+03
 3.9200e+02 2.9600e+02 5.8600e+02 4.5000e+02 6.8900e+02 5.1400e+02
 9.1400e+02 8.6500e+02 7.6500e+02 1.1080e+03 7.6100e+02 1.1450e+03
 7.2200e+02 6.5000e+02 1.1450e+03 6.1700e+02 9.7600e+02 5.2100e+02
 7.6500e+02 1.0660e+03 8.8100e+02 1.1540e+03 1.1090e+03 9.1400e+02
 1.0660e+03 7.4600e+02 1.0250e+03 1.2010e+03 7.2500e+02 7.9400e+02
 1.3010e+03 8.5000e+02 1.5130e+03 1.3600e+03 1.6820e+

In [9]:
tempDist

array([5.338e+03, 3.994e+03, 8.744e+03, 3.845e+03, 5.017e+03, 3.721e+03,
       8.500e+03, 3.924e+03, 8.810e+03, 3.497e+03, 7.325e+03, 4.010e+03,
       7.085e+03, 3.365e+03, 7.333e+03, 3.373e+03, 4.930e+03, 3.349e+03,
       5.234e+03, 3.509e+03, 4.597e+03, 2.925e+03, 7.850e+03, 2.818e+03,
       6.344e+03, 2.536e+03, 4.436e+03, 2.725e+03, 4.426e+03, 2.522e+03,
       7.488e+03, 2.313e+03, 7.209e+03, 2.281e+03, 5.869e+03, 2.050e+03,
       5.417e+03, 1.945e+03, 4.181e+03, 1.682e+03, 3.281e+03, 1.856e+03,
       3.121e+03, 1.746e+03, 3.825e+03, 1.642e+03, 1.885e+03, 2.285e+03,
       2.600e+03, 2.600e+03, 1.872e+03, 1.552e+03, 1.709e+03, 1.481e+03,
       2.186e+03, 2.450e+03, 1.832e+03, 2.056e+03, 1.649e+03, 1.924e+03,
       1.424e+03, 1.465e+03, 1.537e+03, 1.250e+03, 1.525e+03, 1.189e+03,
       1.576e+03, 1.684e+03, 1.189e+03, 1.741e+03, 1.282e+03, 1.997e+03,
       1.513e+03, 1.184e+03, 1.417e+03, 1.060e+03, 1.105e+03, 1.360e+03,
       1.152e+03, 1.732e+03, 1.201e+03, 1.017e+03, 

In [10]:
X-Centroids[:,0]

array([[-14.,   8.],
       [-14.,  50.],
       [-13., -25.],
       [-13.,  46.],
       [-12.,   9.],
       [-12.,  45.],
       [-11., -25.],
       [-11.,  63.],
       [-10., -28.],
       [-10.,  41.],
       [-10., -17.],
       [-10.,  68.],
       [ -9., -16.],
       [ -9.,  46.],
       [ -9., -18.],
       [ -9.,  48.],
       [ -8.,   4.],
       [ -8.,  35.],
       [ -6.,  -2.],
       [ -6.,  67.],
       [ -5.,   4.],
       [ -5.,  42.],
       [ -4., -26.],
       [ -4.,  42.],
       [ -1., -17.],
       [ -1.,  51.],
       [ -1.,   1.],
       [ -1.,  30.],
       [  0.,   0.],
       [  0.,  56.],
       [  1., -27.],
       [  1.,  42.],
       [  4., -27.],
       [  4.,  61.],
       [  4., -17.],
       [  4.,  50.],
       [  5., -14.],
       [  5.,  42.],
       [  8.,  -5.],
       [  8.,  44.],
       [  9.,   4.],
       [  9.,  61.],
       [ 10.,   5.],
       [ 10.,  30.],
       [ 10.,  -3.],
       [ 10.,  34.],
       [ 11.,  24.],
       [ 11.,

In [11]:
print('Centroids[:,0]',Centroids[:,0])
tempDist1 = np.sum((X-Centroids[:,0])**2,axis=1)
tempDist1

Centroids[:,0] [29. 31.]


array([2.6000e+02, 2.6960e+03, 7.9400e+02, 2.2850e+03, 2.2500e+02,
       2.1690e+03, 7.4600e+02, 4.0900e+03, 8.8400e+02, 1.7810e+03,
       3.8900e+02, 4.7240e+03, 3.3700e+02, 2.1970e+03, 4.0500e+02,
       2.3850e+03, 8.0000e+01, 1.2890e+03, 4.0000e+01, 4.5250e+03,
       4.1000e+01, 1.7890e+03, 6.9200e+02, 1.7800e+03, 2.9000e+02,
       2.6020e+03, 2.0000e+00, 9.0100e+02, 0.0000e+00, 3.1360e+03,
       7.3000e+02, 1.7650e+03, 7.4500e+02, 3.7370e+03, 3.0500e+02,
       2.5160e+03, 2.2100e+02, 1.7890e+03, 8.9000e+01, 2.0000e+03,
       9.7000e+01, 3.8020e+03, 1.2500e+02, 1.0000e+03, 1.0900e+02,
       1.2560e+03, 6.9700e+02, 3.7700e+02, 2.4200e+02, 2.4200e+02,
       6.1000e+02, 1.0100e+03, 7.2500e+02, 1.0370e+03, 3.9200e+02,
       2.9600e+02, 5.8600e+02, 4.5000e+02, 6.8900e+02, 5.1400e+02,
       9.1400e+02, 8.6500e+02, 7.6500e+02, 1.1080e+03, 7.6100e+02,
       1.1450e+03, 7.2200e+02, 6.5000e+02, 1.1450e+03, 6.1700e+02,
       9.7600e+02, 5.2100e+02, 7.6500e+02, 1.0660e+03, 8.8100e

In [12]:
EuclidianDistance1=np.array([]).reshape(m,0)
EuclidianDistance1=np.c_[EuclidianDistance,tempDist1]
print(EuclidianDistance1)

[[  260.  1940. 12308.  4573.  5338.   260.]
 [ 2696.  3536.  9704.  8605.  3994.  2696.]
 [  794.  3074. 16634.  3757.  8744.   794.]
 ...
 [11258.  5578.   458.  6245.  2308. 11258.]
 [11833.  6613.  5905.  3636.  6845. 11833.]
 [14368.  7848.   640.  8641.  3530. 14368.]]


In [13]:
EuclidianDistance1

array([[  260.,  1940., 12308.,  4573.,  5338.,   260.],
       [ 2696.,  3536.,  9704.,  8605.,  3994.,  2696.],
       [  794.,  3074., 16634.,  3757.,  8744.,   794.],
       ...,
       [11258.,  5578.,   458.,  6245.,  2308., 11258.],
       [11833.,  6613.,  5905.,  3636.,  6845., 11833.],
       [14368.,  7848.,   640.,  8641.,  3530., 14368.]])

In [14]:
Y={}
for k in range(K):
    Y[k+1]=np.array([]).reshape(2,0) # initialised a map of Cluster and its points
for i in range(m):
    Y[C[i]]=np.c_[Y[C[i]],X[i]]
    #print(Y[C[i]])
for k in range(K):
    Y[k+1]=Y[k+1].T
    
for k in range(K):
     Centroids[:,k]=np.mean(Y[k+1],axis=0)
print(Centroids)

[[ 25.94594595  55.89285714 108.9         89.40625     67.75675676]
 [ 38.37837838  49.91666667  84.2         15.59375     83.40540541]]


In [15]:
for i in range(n_iter):
     #step 2.a
      EuclidianDistance=np.array([]).reshape(m,0)
      for k in range(K):
          tempDist=np.sum((X-Centroids[:,k])**2,axis=1)
          EuclidianDistance=np.c_[EuclidianDistance,tempDist]
      C=np.argmin(EuclidianDistance,axis=1)+1
     #step 2.b
      Y={}
      for k in range(K):
          Y[k+1]=np.array([]).reshape(2,0)
      for i in range(m):
          Y[C[i]]=np.c_[Y[C[i]],X[i]]
     
      for k in range(K):
          Y[k+1]=Y[k+1] .T
    
      for k in range(K):
          [:,k]=np.mean(Y[k+1],axis=0)
      Output=Y

SyntaxError: invalid syntax (<ipython-input-15-00168a78da0f>, line 19)